import { University } from "@/src/types";

export const universities: University[] = [
    {
        id: "1",
        name: "Ulster University",
        country: "United Kingdom",
        city: "London",
        tuitionFee: 14500,
        ranking: 601,
        establishedYear: 1968,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=UU",
        ieltsScore: 6.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Metropolitan",
        courses: ["Computer Science", "Data Science", "MBA", "Health Informatics"],
    },
    {
        id: "2",
        name: "University of Hertfordshire",
        country: "United Kingdom",
        city: "Hatfield",
        tuitionFee: 15200,
        ranking: 801,
        establishedYear: 1952,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=UH",
        ieltsScore: 6.5,
        hasScholarship: true,
        workPermit: true,
        setting: "Suburban",
        courses: ["Cyber Security", "Aerospace Engineering", "Digital Marketing", "Law"],
    },
    {
        id: "3",
        name: "University of Toronto",
        country: "Canada",
        city: "Toronto",
        tuitionFee: 45000,
        ranking: 21,
        establishedYear: 1827,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=UT",
        ieltsScore: 7.0,
        hasScholarship: false,
        workPermit: true,
        setting: "Metropolitan",
        courses: ["Artificial Intelligence", "Robotics", "Economics", "Civil Engineering"],
    },
    {
        id: "4",
        name: "UWE Bristol",
        country: "United Kingdom",
        city: "Bristol",
        tuitionFee: 15750,
        ranking: 401,
        establishedYear: 1992,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=UWE",
        ieltsScore: 6.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Suburban",
        courses: ["Architecture", "Software Engineering", "Environmental Science", "Fine Arts"],
    },
    {
        id: "5",
        name: "Coventry University",
        country: "United Kingdom",
        city: "Coventry",
        tuitionFee: 16800,
        ranking: 651,
        establishedYear: 1992,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=CU",
        ieltsScore: 6.5,
        hasScholarship: true,
        workPermit: true,
        setting: "Town",
        courses: ["Automotive Design", "Biomedical Science", "Business Analytics", "Supply Chain"],
    },
    {
        id: "6",
        name: "McGill University",
        country: "Canada",
        city: "Montreal",
        tuitionFee: 32000,
        ranking: 30,
        establishedYear: 1821,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=MU",
        ieltsScore: 6.5,
        hasScholarship: false,
        workPermit: true,
        setting: "Metropolitan",
        courses: ["Mechanical Engineering", "Psychology", "International Relations", "Finance"],
    },
    {
        id: "7",
        name: "George Brown College",
        country: "Canada",
        city: "Toronto",
        tuitionFee: 15500,
        ranking: 1000,
        establishedYear: 1967,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=GBC",
        ieltsScore: 6.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Metropolitan",
        courses: ["Hospitality Management", "Culinary Arts", "Blockchain Development", "Graphic Design"],
    },
    {
        id: "8",
        name: "University of Portsmouth",
        country: "United Kingdom",
        city: "Portsmouth",
        tuitionFee: 17200,
        ranking: 501,
        establishedYear: 1992,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=UP",
        ieltsScore: 6.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Town",
        courses: ["Criminology", "Marine Biology", "Project Management", "Accounting"],
    },
    {
        id: "9",
        name: "Harvard University",
        country: "USA",
        city: "Cambridge",
        tuitionFee: 54000,
        ranking: 4,
        establishedYear: 1636,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=HU",
        ieltsScore: 7.5,
        hasScholarship: false,
        workPermit: true,
        setting: "Suburban",
        courses: ["Government", "Data Analytics", "Law", "Medicine"],
    },
    {
        id: "10",
        name: "De Montfort University",
        country: "United Kingdom",
        city: "Leicester",
        tuitionFee: 14750,
        ranking: 801,
        establishedYear: 1992,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=DMU",
        ieltsScore: 6.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Town",
        courses: ["Fashion Design", "Pharmacy", "Global Business", "Game Development"],
    },
    {
        id: "11",
        name: "York University",
        country: "Canada",
        city: "Toronto",
        tuitionFee: 28000,
        ranking: 351,
        establishedYear: 1959,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=YU",
        ieltsScore: 6.5,
        hasScholarship: true,
        workPermit: true,
        setting: "Suburban",
        courses: ["Space Science", "Visual Arts", "Human Resources", "Information Technology"],
    },
    {
        id: "12",
        name: "New York University",
        country: "USA",
        city: "New York",
        tuitionFee: 58000,
        ranking: 38,
        establishedYear: 1831,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=NYU",
        ieltsScore: 7.0,
        hasScholarship: false,
        workPermit: true,
        setting: "Metropolitan",
        courses: ["Film & TV", "Media Studies", "Mathematics", "Sociology"],
    },
    {
        id: "13",
        name: "University of East London",
        country: "United Kingdom",
        city: "London",
        tuitionFee: 13500,
        ranking: 901,
        establishedYear: 1992,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=UEL",
        ieltsScore: 5.5,
        hasScholarship: true,
        workPermit: true,
        setting: "Metropolitan",
        courses: ["Sports Science", "Construction Management", "Education", "Psychology"],
    },
    {
        id: "14",
        name: "MIT",
        country: "USA",
        city: "Cambridge",
        tuitionFee: 56000,
        ranking: 1,
        establishedYear: 1861,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=MIT",
        ieltsScore: 7.5,
        hasScholarship: false,
        workPermit: true,
        setting: "Suburban",
        courses: ["Quantum Computing", "Electrical Engineering", "Physics", "Architecture"],
    },
    {
        id: "15",
        name: "Anglia Ruskin University",
        country: "United Kingdom",
        city: "Cambridge",
        tuitionFee: 15000,
        ranking: 351,
        establishedYear: 1992,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=ARU",
        ieltsScore: 6.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Town",
        courses: ["Optometry", "Music Therapy", "Animal Behavior", "Nursing"],
    },
    {
        id: "16",
        name: "Concordia University",
        country: "Canada",
        city: "Montreal",
        tuitionFee: 24000,
        ranking: 521,
        establishedYear: 1974,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=CU",
        ieltsScore: 6.5,
        hasScholarship: true,
        workPermit: true,
        setting: "Metropolitan",
        courses: ["Journalism", "Industrial Engineering", "Software Systems", "Linguistics"],
    },
    {
        id: "17",
        name: "University of North Texas",
        country: "USA",
        city: "Denton",
        tuitionFee: 21000,
        ranking: 801,
        establishedYear: 1890,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=UNT",
        ieltsScore: 6.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Town",
        courses: ["Jazz Studies", "Library Science", "Emergency Management", "Aviation"],
    },
    {
        id: "18",
        name: "Birmingham City University",
        country: "United Kingdom",
        city: "Birmingham",
        tuitionFee: 14500,
        ranking: 601,
        establishedYear: 1992,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=BCU",
        ieltsScore: 6.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Metropolitan",
        courses: ["Jewellery Design", "Acting", "Big Data", "Real Estate"],
    },
    {
        id: "19",
        name: "University of Waterloo",
        country: "Canada",
        city: "Waterloo",
        tuitionFee: 42000,
        ranking: 112,
        establishedYear: 1957,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=UW",
        ieltsScore: 7.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Suburban",
        courses: ["Actuarial Science", "Nanotechnology", "Computer Engineering", "Statistics"],
    },
    {
        id: "20",
        name: "Texas A&M University",
        country: "USA",
        city: "College Station",
        tuitionFee: 38000,
        ranking: 134,
        establishedYear: 1876,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=TAMU",
        ieltsScore: 6.5,
        hasScholarship: false,
        workPermit: true,
        setting: "Town",
        courses: ["Petroleum Engineering", "Agriculture", "Veterinary Medicine", "Management"],
    },
    {
        id: "21",
        name: "Middlesex University",
        country: "United Kingdom",
        city: "London",
        tuitionFee: 14000,
        ranking: 701,
        establishedYear: 1973,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=MU",
        ieltsScore: 6.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Metropolitan",
        courses: ["Information Systems", "Creative Writing", "Social Work", "Mechatronics"],
    },
    {
        id: "22",
        name: "Humber College",
        country: "Canada",
        city: "Toronto",
        tuitionFee: 16500,
        ranking: 1001,
        establishedYear: 1967,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=HC",
        ieltsScore: 6.0,
        hasScholarship: true,
        workPermit: true,
        setting: "Suburban",
        courses: ["Interior Design", "Public Relations", "Fashion Management", "Cloud Computing"],
    },
    {
        id: "23",
        name: "Stanford University",
        country: "USA",
        city: "Stanford",
        tuitionFee: 56000,
        ranking: 3,
        establishedYear: 1885,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=SU",
        ieltsScore: 7.5,
        hasScholarship: false,
        workPermit: true,
        setting: "Suburban",
        courses: ["Political Science", "Philosophy", "Structural Biology", "Computer Science"],
    }
];